export const tornErrorCodes: Record<number, string> = {
    0: "Unknown error",
    1: "Key is empty",
    2: "Incorrect Key",
    3: "Wrong type",
    4: "Wrong fields",
    5: "Too many requests",
    6: "Incorrect ID",
    7: "Incorrect ID-entity relation",
    8: "IP block",
    9: "API disabled",
    10: "Key owner is in federal jail",
    11: "Key change error",
    12: "Key read error",
    13: "Key temporarily disabled due to inactivity",
    14: "Daily read limit reached",
    15: "Temporary error",
    16: "Key access level too low",
    17: "Backend error occurred",
    18: "API key paused by owner",
    19: "Must migrate to crimes 2.0",
    20: "Race not yet finished",
    21: "Incorrect category",
    22: "Selection only in API v1",
    23: "Selection only in API v2",
    24: "Closed temporarily",
  };